version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    hostname: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_net

  db_client:
    image: dpage/pgadmin4:7.8
    container_name: db_client
    hostname: db-client
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    volumes:
      - db_client:/var/lib/pgadmin
    networks:
      - db_net

volumes:
  db:
  db_client:
networks:
  db_net:
